[package]
name = "zinc-tester"
version = "0.2.1"
authors = [
    "Alex Zarudnyy <a.zarudnyy@matterlabs.dev>",
]
edition = "2018"
description = "The Zinc integration test runner"

[[bin]]
name = "zinc-tester"
path = "src/zinc-tester/main.rs"

[dependencies]
structopt = "0.3"
anyhow = "1.0"
thiserror = "1.0"
colored = "2.0"

serde = "1.0"
serde_json = "1.0"
semver = "0.11"
num = "0.3"

tokio = "0.2"
rayon = "1.5"

zksync = { git = "https://github.com/vikkkko/zksyncM.git", branch = "master" }
zksync_types = { git = "https://github.com/vikkkko/zksyncM.git", branch = "master" }

zinc-const = { path = "../zinc-const" }
zinc-project = { path = "../zinc-project" }
zinc-compiler = { path = "../zinc-compiler" }
zinc-types = { path = "../zinc-types" }
zinc-vm = { path = "../zinc-vm" }
zinc-logger =  { path = "../zinc-logger" }

zargo = { path = "../zargo" }
